package com.ajiatech.mapper;

import com.ajiatech.pojo.AjiaOrderItem;
import com.ajiatech.pojo.AjiaOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AjiaOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order_item
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    long countByExample(AjiaOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order_item
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int deleteByExample(AjiaOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order_item
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order_item
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int insert(AjiaOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order_item
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int insertSelective(AjiaOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order_item
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    List<AjiaOrderItem> selectByExample(AjiaOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order_item
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    AjiaOrderItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order_item
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") AjiaOrderItem record, @Param("example") AjiaOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order_item
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByExample(@Param("record") AjiaOrderItem record, @Param("example") AjiaOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order_item
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByPrimaryKeySelective(AjiaOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order_item
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByPrimaryKey(AjiaOrderItem record);
}