package com.ajiatech.mapper;

import com.ajiatech.pojo.AjiaItemDesc;
import com.ajiatech.pojo.AjiaItemDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AjiaItemDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    long countByExample(AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int deleteByExample(AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int insert(AjiaItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int insertSelective(AjiaItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    List<AjiaItemDesc> selectByExampleWithBLOBs(AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    List<AjiaItemDesc> selectByExample(AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    AjiaItemDesc selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") AjiaItemDesc record, @Param("example") AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") AjiaItemDesc record, @Param("example") AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByExample(@Param("record") AjiaItemDesc record, @Param("example") AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByPrimaryKeySelective(AjiaItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(AjiaItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByPrimaryKey(AjiaItemDesc record);
}