package com.ajiatech.mapper;

import com.ajiatech.pojo.AjiaUser;
import com.ajiatech.pojo.AjiaUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AjiaUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_user
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    long countByExample(AjiaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_user
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int deleteByExample(AjiaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_user
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_user
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int insert(AjiaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_user
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int insertSelective(AjiaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_user
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    List<AjiaUser> selectByExample(AjiaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_user
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    AjiaUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_user
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") AjiaUser record, @Param("example") AjiaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_user
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByExample(@Param("record") AjiaUser record, @Param("example") AjiaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_user
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByPrimaryKeySelective(AjiaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_user
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByPrimaryKey(AjiaUser record);
}