package com.ajiatech.mapper;

import com.ajiatech.pojo.AjiaItemCat;
import com.ajiatech.pojo.AjiaItemCatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AjiaItemCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_cat
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    long countByExample(AjiaItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_cat
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int deleteByExample(AjiaItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_cat
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_cat
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int insert(AjiaItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_cat
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int insertSelective(AjiaItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_cat
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    List<AjiaItemCat> selectByExample(AjiaItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_cat
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    AjiaItemCat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_cat
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") AjiaItemCat record, @Param("example") AjiaItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_cat
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByExample(@Param("record") AjiaItemCat record, @Param("example") AjiaItemCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_cat
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByPrimaryKeySelective(AjiaItemCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_cat
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByPrimaryKey(AjiaItemCat record);
}