package com.ajiatech.mapper;

import com.ajiatech.pojo.AjiaOrder;
import com.ajiatech.pojo.AjiaOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AjiaOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    long countByExample(AjiaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int deleteByExample(AjiaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int insert(AjiaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int insertSelective(AjiaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    List<AjiaOrder> selectByExample(AjiaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    AjiaOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") AjiaOrder record, @Param("example") AjiaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByExample(@Param("record") AjiaOrder record, @Param("example") AjiaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByPrimaryKeySelective(AjiaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_order
     *
     * @mbg.generated Wed Dec 20 14:19:38 CST 2017
     */
    int updateByPrimaryKey(AjiaOrder record);
}